### ISSUE TITLE
Create docker images for open liberty

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/ci.docker#1]
We need some docker images for Open Liberty. There are already docker images for WebSphere Liberty, but we should have them from Open Liberty too.

Some things to consider:

- Which JVM to use. IBM, Oracle, OpenJDK+OpenJ9, OpenJDK+HotSpot
- Which server templates to use
- Which architectures

It would be good to keep things simple, but [issue 8](https://github.com/OpenLiberty/open-liberty/issues/169) over in the open-liberty repository is discussing what the default server template should be so this should provide input.

We only really want one image in docker hub, so I think we need tags to select from these different considerations.

**Comment by NottyCode** [comment]
I'm going to suggest that we go with the following tags:

kernel: - comes with all the code, but server.xml is configured with nothing allowing full customization.
microProfile1: - comes with all the code, and a server.xml configured with microProfile-1.2
webProfile7: - comes with all the code and a server.xml configured for web profile version 7.
javaee7: - comes with all the code and a server.xml configured for all of java ee 7. Will need to have an SSL certificate generated for this case since it is required for remote EJB support. This should be done on startup.

One advantage of this is it makes it easy to switch between the existing websphere-liberty to the new open-liberty by just changing the FROM statement.

**Comment by davidcurrie** [comment]
Looks reasonable to me although note that websphere-liberty uses microProfile not microProfile1. For multiple architectures, Docker are building images in to different namespaces (e.g. ppc64le/open-liberty) and then putting a multi-arch manifest in to the default namespace.

**Comment by NottyCode** [comment]
@davidcurrie I wanted to use something different from microProfile as a tag because the websphere-liberty:microProfile uses microProfile-1.0 and these will use microProfile-1.2 which is a big difference in function.

I saw there was some thing in the build script for websphere liberty where you create a tag based on the current os arch of ibmjava mapped to arch/ibmjava. I assumed that was the magic sauce.

**Comment by davidcurrie** [comment]
@NottyCode - how's that going to work going forwards? Is microProfile-1.3 not going to be an equally large leap? And whatever happened to semantic versioning!

The multi-arch stuff in ci.docker isn't actually needed any more - we should take it out. Docker build the images for all platforms and the 'FROM ibmjava' now just pulls the right image for the platform you're building on.

**Comment by NottyCode** [comment]
@davidcurrie That is a fair point, however microProfile-1.x and microProfile-2.x are not going to be fully compatible and there is a lot of talk about doing 2.0 to pull in the EE 8 versions of CDI, JAX-RS, JSON-P and JSON-B plus possibly security. From that perspective I'm very nervous about having a microProfile without a version since it'll be obsolete when 2.0 comes out which I suspect will be early next year.

Cool, that makes things simpler then.

**Comment by NottyCode** [comment]
I just delivered some Dockerfiles based on the proposal above.

This isn't "final" by any means, just wanted to start with a proposal. Open Liberty should also get some default tempates, so we can just do server create --template=<microProfile1|webProfile7|javaee7]

**Comment by davidcurrie** [comment]
@NottyCode - I notice you're still using the path /opt/ibm which would give compatibility with the websphere-liberty images but was wondering to what extent you wanted these to be 'IBM free'?

**Comment by NottyCode** [comment]
@davidcurrie that is a good point. Any comments on the SSL changes I made to docker-server?

**Comment by tnsasse** [comment]
+1 for having different base images extending the kernel image
+1 to base off of ibmjava kit

Couple of thoughts:
- I'd like to have tags for each kernel version, this will help ops teams to methodically update their running containers and gives them the ability to rollback to a known good version. I don't imagine everyone should just use "latest", at least in enterprise scenarios we often see staging processes applied. (This is of course only a question on how we push stuff to docker hub)
- I think we should export a DEPLOYMENT_DIR variable, such that it becomes easier for people to build their own app-specific docker images (I will open a PR)
- It's best practice to put a MAINTAINER in the Dockerfiles, which is missing as of now, @NottyCode I would suggest at least pointing to GitHub / the community...
- I think it's worth considering `ibmjava:8-sfj` instead of `ibmjava:8-jre`which reduces the image size by ~100MB, which is nice for people on weak internet connections / accelerates initial cloud deployments. I have done some initial testing and it worked well for my use cases, but I am unsure about other people's needs, so I love to hear your feedback. Please see the documentation for more details: [IBM Small Footprint JRE](https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.lnx.80.doc/user/small_jre.html)
- Eventually, I would suggest migrating to [Eclipse OpenJ9](http://www.eclipse.org/openj9/)

Good job and thanks @NottyCode

**Comment by NottyCode** [comment]
1) I think that is just getting the right tags when the build occurs. I've found this wiki page that says how to make it happen: http://windsock.io/automated-docker-image-builds-with-multiple-tags/

2) I'm of two minds on a DEPLOYMENT_DIR pointing at dropins because I prefer to encourage people to deploy in the apps folder and using server.xml configuration. If we do this we should probably also have variables for a few other locations, like the config dir, and config dropins dirs.

3) It seems MAINTAINER has been deprecated https://docs.docker.com/engine/reference/builder/#maintainer-deprecated Adding the suggested label works, but it makes me wonder what other ones would make sense. 

4) I hadn't even heard of sfj. I'll take a look at what it would mean.

5) I'd love to use Eclipse OpenJ9, but right now I would need an Open J9 docker images that runs OpenJDK 8. As soon as we can switch to Eclipse Open J9 I'll do that.

**Comment by tnsasse** [comment]
Thanks for your feedback. I totally agree with OpenJ9. 

I see what you mean with the env variables and it makes me reconsider my stance on the matter. I elaborated on this a bit more in the PR.

**Comment by NottyCode** [comment]
Because we see a future need to support for different Java version's I've added some docker files that deal with different variant's of the JVM. Currently there is only Java 8 for IBM and IBM SFJ. As a tag naming convention I'm thinking:

    <type>-java<version>-<vendor>

so we would have tags like kernel-java8-ibm or webProfile7-java9-openj9. I haven't setup for these new images to get into dockerhub on the basis that we should probably discuss before making them happen.

Alasdair
