### ISSUE TITLE
Open liberty full docker image does not contain Microprofile specifications

### ISSUE THREAD

**Issue by NickWemekamp** [OpenLiberty/ci.docker#260]
When I run `docker run open-liberty:21.0.0.4-full-java8-openj9` on my machine I see that open liberty has installed the following features:

`[appClientSupport-1.0, appSecurity-2.0, appSecurity-3.0, batch-1.0, beanValidation-2.0, cdi-2.0, concurrent-1.0, distributedMap-1.0, ejb-3.2, ejbHome-3.2, ejbLite-3.2, ejbPersistentTimer-3.2, ejbRemote-3.2, el-3.0, j2eeManagement-1.1, jacc-1.5, jaspic-1.1, javaMail-1.6, javaee-8.0, jaxb-2.2, jaxrs-2.1, jaxrsClient-2.1, jaxws-2.2, jca-1.7, jcaInboundSecurity-1.0, jdbc-4.2, jms-2.0, jndi-1.0, jpa-2.2, jpaContainer-2.2, jsf-2.3, jsonb-1.0, jsonp-1.1, jsp-2.3, managedBeans-1.0, mdb-3.2, servlet-4.0, ssl-1.0, wasJmsClient-2.0, wasJmsSecurity-1.0, wasJmsServer-1.0, webProfile-8.0, websocket-1.1].`

Note that the Microprofile features are missing and I was curious if this is the expected behaviour.

**Comment by jdmcclur** [comment]
Yes, this is expected behavior.

The Microprofile features are actually in the image, but they are not enabled by default.

The full image has the following in its server.xml by default, which does not include the MicroProfile features.
```
<!-- Enable features -->
    <featureManager>
        <feature>javaee-8.0</feature>
    </featureManager>
```

Best practice is to supply your own server.xml, so if you change to these features and build a layer on top, they will be enabled.

```
<!-- Enable features -->
  <featureManager>
    <feature>microProfile-4.0</feature>
  </featureManager>
```


Example Dockerfile
```
FROM open-liberty:full
COPY --chown=1001:0 server.xml /config/server.xml
```

**Comment by NickWemekamp** [comment]
Thanks! This clarifies it a lot.
